name: nutrition-service

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "nutrition-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=postgres
      - CLICKHOUSE_PASSWORD=postgres
      - CLICKHOUSE_DB=nutrition_db
    ports:
      - "8123:8123"
      - "9000:9000"