name: nutrition-service

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "nutrition-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=postgres
      - CLICKHOUSE_PASSWORD=postgres
      - CLICKHOUSE_DB=nutrition_db
    ports:
      - "8123:8123"
      - "9000:9000"
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    restart: always
    ports:
      - "6379:6379"
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    healthcheck:
      test: [ "CMD", "keydb-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
  redis-cli:
    image: redis:latest
    container_name: redis-cli
    depends_on:
      - keydb
    entrypoint: [ "tail", "-f", "/dev/null" ] # чтобы контейнер не завершался сразу
    networks:
      - default